### ISSUE TITLE
Tensorflow and keras version

### ISSUE THREAD

**Issue by deepzx987** [philipperemy/deep-speaker#41]
Which version of tensorflow and keras are you using??
I am getting this error while executing your code:
Traceback (most recent call last):
  File "train_cli.py", line 245, in <module>
    start_training()
  File "train_cli.py", line 207, in start_training
    kx_train, ky_train, kx_test, ky_test, categorical_speakers = data_to_keras(data)
  File "/home/deepankar/deep-speaker/utils.py", line 15, in data_to_keras
    categorical_speakers = SpeakersToCategorical(data)
  File "/home/deepankar/deep-speaker/utils.py", line 169, in __init__
    self.speaker_categories = to_categorical(self.int_speaker_ids, num_classes=len(self.speaker_ids), dtype='float32')
  File "/home/deepankar/venv-speaker/lib/python3.6/site-packages/keras/utils/np_utils.py", line 31, in to_categorical
    num_classes = np.max(y) + 1
  File "/home/deepankar/venv-speaker/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2505, in amax
    initial=initial)
  File "/home/deepankar/venv-speaker/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

**Comment by philipperemy** [comment]
@deepzx987 

```
Keras                  2.2.4
tensorflow             1.8.0
```

But I guess other versions should work!
