### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by ooobsidian** [philipperemy/deep-speaker#49]
hello，when I run `python cli.py --unseen_speakers p363,p364 --audio_dir $AUDIO_DIR --cache_output_dir $CACHE_DIR`, it gives me an error
```
$ python cli.py --unseen_speakers p363,p364 --audio_dir $AUDIO_DIR --cache_output_dir $CACHE_DIR
2019-10-24 21:13:18,326 - INFO - audio_dir = /Users/obsidian/deep-speaker-data/VCTK-Corpus/
2019-10-24 21:13:18,326 - INFO - cache_dir = /Users/obsidian/deep-speaker-data/cache/
2019-10-24 21:13:18,326 - INFO - sample_rate = 8000
Using TensorFlow backend.
Traceback (most recent call last):
  File "cli.py", line 83, in <module>
    main()
  File "cli.py", line 71, in main
    inference_unseen_speakers(audio_reader, unseen_speakers[0], unseen_speakers[1])
  File "/Users/obsidian/source/deep-speaker/unseen_speakers.py", line 33, in inference_unseen_speakers
    sp1_feat = generate_features_for_unseen_speakers(audio_reader, target_speaker=sp1)
  File "/Users/obsidian/source/deep-speaker/unseen_speakers.py", line 22, in generate_features_for_unseen_speakers
    assert target_speaker in audio_reader.all_speaker_ids
AssertionError
```

How can I solve this problem?
Thank you！

**Comment by ooobsidian** [comment]
solved！

**Comment by lecidhugo** [comment]
Hi @ooobsidian,
How did you manage to solve it ? I am facing the same problem.
Thank you!,

**Comment by ooobsidian** [comment]
Do it step by step,do not "Generate embeddings with a pre-trained network" at first, 
you can "generate audio caches" at first and "Generate embeddings with a pre-trained network" next.
