### ISSUE TITLE
counts_per_speaker

### ISSUE THREAD

**Issue by ooobsidian** [philipperemy/deep-speaker#55]
Could you tell me about `--counts_per_speaker`? I want to train on my own dataset, but I don't know how to use it.

**Comment by philipperemy** [comment]
@ooobsidian sure. counts_per_speaker is the number of samples to generate for the train and test sets.

If you specify `--counts_per_speaker 600,100`, that means for each speaker, you're going to generate 600 samples for training and 100 for testing. One sample is 160 frames by default (~roughly 1.6 seconds).

**Comment by ooobsidian** [comment]
When I run `./deep-speaker build-keras-inputs`, when one iteration is over, it got an error:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cli.py", line 96, in <module>
    cli()
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "cli.py", line 92, in train_model
    start_training(working_dir, pre_training_phase)
  File "/data/source/deep-speaker/train.py", line 93, in start_training
    fit_model_softmax(dsm, kc.kx_train, kc.ky_train, kc.kx_test, kc.ky_test, initial_epoch=initial_epoch)
  File "/data/source/deep-speaker/train.py", line 72, in fit_model_softmax
    callbacks=[early_stopping, reduce_lr, checkpoint])
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 395, in fit
    total_epochs=1)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 152, in run_one_epoch
    total_epochs * steps_per_epoch))
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
```

**Comment by philipperemy** [comment]
@ooobsidian seems like `total_epochs` or `steps_per_epoch` is None.

**Comment by ooobsidian** [comment]
THX, I wonder when the training softmax will be ready to take the next step?

**Comment by philipperemy** [comment]
Not sure where it comes from. I've never encountered this..

**Comment by ooobsidian** [comment]
I mean what indicators need to be achieved in `./deep-speaker train_softmax` before the `./deep-speaker train_triplet`.

**Comment by philipperemy** [comment]
I can reach something like  train_accuracy: 0.998 and test_accuracy: 0.990. From there, I stopped and started the train_triplet command.

**Comment by ooobsidian** [comment]
OK, thanks!

**Comment by philipperemy** [comment]
@ooobsidian welcome!

**Comment by ooobsidian** [comment]
Hello, when I run `./deep-speaker train_triplet`, an error has occurred.
```
Traceback (most recent call last):
  File "cli.py", line 96, in <module>
    cli()
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "cli.py", line 92, in train_model
    start_training(working_dir, pre_training_phase)
  File "/data/source/deep-speaker/train.py", line 109, in start_training
    fit_model(dsm, working_dir, NUM_FRAMES)
  File "/data/source/deep-speaker/train.py", line 21, in fit_model
    batcher = LazyTripletBatcher(working_dir, max_length, dsm)
  File "/data/source/deep-speaker/batcher.py", line 179, in __init__
    self.update_triplets_history()
  File "/data/source/deep-speaker/batcher.py", line 196, in update_triplets_history
    embeddings = self.model.m.predict(np.array(model_inputs))
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 1013, in predict
    use_multiprocessing=use_multiprocessing)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 498, in predict
    workers=workers, use_multiprocessing=use_multiprocessing, **kwargs)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 426, in _model_iteration
    use_multiprocessing=use_multiprocessing)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 646, in _process_inputs
    x, y, sample_weight=sample_weights)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 2383, in _standardize_user_data
    batch_size=batch_size)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 2410, in _standardize_tensors
    exception_prefix='input')
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_utils.py", line 573, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input to have 4 dimensions, but got array with shape (0, 1)
```
Can you help me?

**Comment by philipperemy** [comment]
@ooobsidian Seems like when you're running the triplet training, your folder containing the triplets is empty?

**Comment by ooobsidian** [comment]
yes, my `deep-speaker` file is 
```
#!/usr/bin/env bash

set -e

HOME_DIR='/data/source/deep-speaker'
WORKING_DIR="${HOME_DIR}/.deep-speaker-wd"

if [ $# -lt 1 ]; then
  echo "Usage : $0 Task [download_librispeech, build_mfcc, build_model_inputs, train_softmax, train_triplet]"
  exit
fi

PRE_TRAINING_WORKING_DIR="${WORKING_DIR}/pre-training"
TRIPLET_TRAINING_WORKING_DIR="${WORKING_DIR}/triplet-training"

mkdir -p "${WORKING_DIR}"

case "$1" in

download_librispeech)
  echo "[download_librispeech] selected."
  # WORKING_DIR/LibriSpeech
  cp download_librispeech.sh "${WORKING_DIR}"
  cd "${WORKING_DIR}" && bash download_librispeech.sh && cd -
  ;;

build_mfcc)
  echo "[build_mfcc] selected."
  python cli.py build-mfcc-cache --working_dir "${PRE_TRAINING_WORKING_DIR}" --audio_dir "/data/source/voiceprint_asr_train_20200403/wav/deep-speaker-1000/wav"
  # python cli.py build-mfcc-cache --working_dir "${TRIPLET_TRAINING_WORKING_DIR}" --audio_dir "${WORKING_DIR}/LibriSpeech"
  ;;

build_model_inputs)
  echo "[build_model_inputs] selected."
  python cli.py build-keras-inputs --working_dir "${PRE_TRAINING_WORKING_DIR}"
  ;;

train_softmax)
  # Pre-training (0.92k speakers).
  echo "[train_softmax] selected."
  python cli.py train-model --working_dir "${PRE_TRAINING_WORKING_DIR}" --pre_training_phase
  ;;

train_triplet)
  # Triplet-training (2.48k speakers).
  echo "[train_triplet] selected."
  python cli.py train-model --working_dir "${TRIPLET_TRAINING_WORKING_DIR}"
  ;;

*)
  echo "Unknown option."
  ;;

esac
```

I follow your README.md, but it doesn't work.

**Comment by ooobsidian** [comment]
Should I rerun the command `python cli.py build-mfcc-cache --working_dir "${TRIPLET_TRAINING_WORKING_DIR}" --audio_dir "/data/source/voiceprint_asr_train_20200403/wav/deep-speaker-1000/wav"` ？

**Comment by xyj0880** [comment]
> When I run `./deep-speaker build-keras-inputs`, when one iteration is over, it got an error:
> 
> ```
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "cli.py", line 96, in <module>
>     cli()
>   File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "cli.py", line 92, in train_model
>     start_training(working_dir, pre_training_phase)
>   File "/data/source/deep-speaker/train.py", line 93, in start_training
>     fit_model_softmax(dsm, kc.kx_train, kc.ky_train, kc.kx_test, kc.ky_test, initial_epoch=initial_epoch)
>   File "/data/source/deep-speaker/train.py", line 72, in fit_model_softmax
>     callbacks=[early_stopping, reduce_lr, checkpoint])
>   File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 819, in fit
>     use_multiprocessing=use_multiprocessing)
>   File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 395, in fit
>     total_epochs=1)
>   File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 152, in run_one_epoch
>     total_epochs * steps_per_epoch))
> TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
> ```

Hi , when I run, ./deep-speaker build_mfcc , I get an error. 
Can you help me?

[build_mfcc] selected.
Using TensorFlow backend.
Traceback (most recent call last):
  File "cli.py", line 96, in <module>
    cli()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "cli.py", line 41, in build_audio_cache
    Audio(cache_dir=working_dir, audio_dir=audio_dir, sample_rate=sample_rate)
  File "/data/speaker-recognition/deep-speaker/audio.py", line 46, in __init__
    self.build_cache(os.path.expanduser(audio_dir), sample_rate)
  File "/data/speaker-recognition/deep-speaker/audio.py", line 86, in build_cache
    assert audio_files_count != 0, 'Could not find any {self.ext} files in {audio_dir}.'
AssertionError: Could not find any {self.ext} files in {audio_dir}.

**Comment by philipperemy** [comment]
@ooobsidian Ah yeah that's why. You have FLAC or WAV? This code expects FLAC extension!
I stopped using WAV because it takes too much space. FLAC is compressed WAV.
When you download LibriSpeech, it's FLAC by default.
I think it should solve your problem!!

**Comment by ooobsidian** [comment]
I used my own dataset, it’s way.

**Comment by philipperemy** [comment]
AAhh then code needs to be edited a bit. just replace all flac by wav in the code. It will work the same way.

**Comment by philipperemy** [comment]
https://stackoverflow.com/questions/1585170/how-to-find-and-replace-all-occurrences-of-a-string-recursively-in-a-directory-t

flac -> wav
FLAC -> WAV

**Comment by philipperemy** [comment]
I'll add the support of wav too :)

**Comment by philipperemy** [comment]
Thanks for checking the code by the way!

**Comment by ooobsidian** [comment]
thank you very much！

**Comment by ooobsidian** [comment]
One last question, when can triplet loss training stop? Here is my situation.
```
Epoch 17/1000
2000/2000 [==============================] - 326s 163ms/step - loss: 0.0383 - val_loss: 0.0379
```

**Comment by philipperemy** [comment]
@ooobsidian it never stops in my opinion. I stopped it but it was still decreasing. It takes a long time. My training logs are here:

- Softmax pre-training: https://docs.google.com/document/d/1ZZjBk5TgFgaY9GgOcHaieOpiyB9lB6oTRSdk6g8FPRs/edit
- Triplet training: https://docs.google.com/document/d/1mL0Jb8IpA7DOzFci71RT1OYTq7Kkw2DjTkI4BRpEzKc

**Comment by ooobsidian** [comment]
thanks, I see.

**Comment by ooobsidian** [comment]
I'm sorry to bother you again. I referred to your code in readme.md when I tested it, and my test file content is follow:
```
import random
import os
import numpy as np
from tqdm import tqdm
from audio import read_mfcc
from batcher import sample_from_mfcc
from constants import SAMPLE_RATE, NUM_FRAMES
from conv_models import DeepSpeakerModel
from sklearn.metrics.pairwise import cosine_similarity
# from test import batch_cosine_similarity
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
# Reproducible results.
np.random.seed(123)
random.seed(123)


def load_model():
    # Define the model here.
    model = DeepSpeakerModel()
    # Load the checkpoint.
    model.m.load_weights(
        '/data/source/deep-speaker/checkpoints-triplets/ResCNN_checkpoint_331.h5',
        by_name=True)
    return model


def get_per_speaker_embedding(filename):
    model = load_model()
    mfcc = sample_from_mfcc(read_mfcc(filename, SAMPLE_RATE), NUM_FRAMES)
    embedding = model.m.predict(np.expand_dims(mfcc,
                                               axis=0)).flatten()  # (512,)
    return embedding


def embedding_average(path):
    audio_list = os.listdir(path)
    sum = [0 for _ in range(512)]
    for idx, audio in enumerate(audio_list):
        tmp = get_per_speaker_embedding(path + '/' + audio)
        if idx == 0:
            sum += tmp
        else:
            sum = (sum + tmp) / 2.0
    return sum


def embedding_concatenate(path):
    audio_list = os.listdir(path)
    sum = [0 for _ in range(512)]
    for idx, audio in enumerate(audio_list):
        tmp = get_per_speaker_embedding(path + '/' + audio)
        if idx == 0:
            sum += tmp
        else:
            sum = np.concatenate((sum, tmp))
    return sum


def get_register(
        base_path='/data/source/cross_validation_test/new_data/register/',
        out_path='register_emb/'):
    register_files = os.listdir(base_path)
    if not os.path.exists(out_path):
        os.mkdir(out_path)
    for spk in tqdm(register_files):
        # ====== 1
        emb = embedding_average(base_path + spk)
        # ====== 2
        # emb = embedding_concatenate(base_path + spk)
        # print('register shape:', emb.size)
        if not os.path.exists(out_path + spk):
            os.mkdir(out_path + spk)
        target_filename = out_path + spk + '/' + spk + '.npy'
        np.save(target_filename, emb)


def get_validate(
        base_path='/data/source/cross_validation_test/new_data/verify/',
        out_path='validate_emb/'):
    spk_list = os.listdir(base_path)
    if not os.path.exists(out_path):
        os.mkdir(out_path)
    for spk in tqdm(spk_list):
        tmp_list = os.listdir(base_path + spk)
        for i in tmp_list:
            emb = get_per_speaker_embedding(base_path + spk + '/' + i)
            # ====== 1
            # ====== 2
            # emb = np.concatenate((emb, emb))
            # print('validate shape:', emb.shape)
            if not os.path.exists(out_path + spk):
                os.mkdir(out_path + spk)
            target_filename = out_path + spk + '/' + i.split('.')[0] + '.npy'
            np.save(target_filename, emb)


def cross_validation():
    AUDIO_DIR = 'validate_emb/'
    REGISTER_DIR = 'register_emb/'
    spk_list = os.listdir(AUDIO_DIR)
    register_list = os.listdir(REGISTER_DIR)
    # print('spk_list: ', spk_list)
    # print('register_list: ', register_list)
    ans = ''
    for spk1 in tqdm(spk_list):
        test_files = os.listdir(AUDIO_DIR + spk1)
        for i in test_files:
            ans = ''
            emb1 = np.load(AUDIO_DIR + spk1 + '/' + i)
            for spk2 in register_list:
                verify_files = os.listdir(REGISTER_DIR + spk2)
                for j in verify_files:
                    emb2 = np.load(REGISTER_DIR + spk2 + '/' + j)
                    # print('emb2:', emb2.shape)
                    ans += str(1 -
                               cosine_similarity([emb1, emb2])[0][1]) + '\t'
            # print(ans)
            with open('ans.txt', 'a') as f:
                f.write(ans + '\n')

if __name__ == '__main__':
    get_register()
    get_validate()
    cross_validation()
```
And when the `get_register()` function is executed, after running for a while, it will occur an error:
```
Using TensorFlow backend.
 12%|██████████████▌                                                                                                         | 51/419 [03:33<25:39,  4.18s/it]
Traceback (most recent call last):
  File "cross_validation.py", line 131, in <module>
    get_register()
  File "cross_validation.py", line 70, in get_register
    emb = embedding_average(base_path + spk)
  File "cross_validation.py", line 41, in embedding_average
    tmp = get_per_speaker_embedding(path + '/' + audio)
  File "cross_validation.py", line 28, in get_per_speaker_embedding
    model = load_model()
  File "cross_validation.py", line 19, in load_model
    model = DeepSpeakerModel()
  File "/data/source/deep-speaker/conv_models.py", line 52, in __init__
    x = self.cnn_component(inputs)
  File "/data/source/deep-speaker/conv_models.py", line 135, in cnn_component
    x = self.conv_and_res_block(x, 512, stage=4)
  File "/data/source/deep-speaker/conv_models.py", line 124, in conv_and_res_block
    kernel_regularizer=regularizers.l2(l=0.0001), name=conv_name)(inp)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 748, in __call__
    self._maybe_build(inputs)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2116, in _maybe_build
    self.build(input_shapes)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/convolutional.py", line 158, in build
    dtype=self.dtype)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 446, in add_weight
    caching_device=caching_device)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/training/tracking/base.py", line 744, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py", line 142, in make_variable
    shape=variable_shape if variable_shape else None)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 258, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 219, in _variable_v1_call
    shape=shape)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 197, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/ops/variable_scope.py", line 2596, in default_variable_creator
    shape=shape)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 262, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 1411, in __init__
    distribute_strategy=distribute_strategy)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 1542, in _init_from_args
    initial_value() if init_from_fn else initial_value,
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py", line 122, in <lambda>
    init_val = lambda: initializer(shape, dtype=dtype)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/ops/init_ops_v2.py", line 425, in __call__
    return self._random_generator.random_uniform(shape, -limit, limit, dtype)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/ops/init_ops_v2.py", line 788, in random_uniform
    shape=shape, minval=minval, maxval=maxval, dtype=dtype, seed=self.seed)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/ops/random_ops.py", line 273, in random_uniform
    result = math_ops.add(rnd * (maxval - minval), minval, name=name)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_math_ops.py", line 343, in add
    _ops.raise_from_not_ok_status(e, name)
  File "/root/miniconda3/envs/3.6.7/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 6606, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[5,5,256,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:Add] name: conv512-s_103/kernel/Initializer/random_uniform/
```
I know it's an OOM error, but I don't know how to fix it? Can you help me please?
