### ISSUE TITLE
RuntimeError: cannot join current thread

### ISSUE THREAD

**Issue by wenku1992abc** [philipperemy/deep-speaker#78]
user9@puser-DGX-Station:/raid/user9/workspace/ASR/SpeakerVerification/deep-speaker-master$ CUDA_VISIBLE_DEVICES=2,3 python cli.py build-keras-inputs --working_dir "/raid/user9/workspace/ASR/SpeakerVerification/deep-speaker-master/pre-training/"
Using TensorFlow backend.
>>>>1 /raid/user9/workspace/ASR/SpeakerVerification/deep-speaker-master/pre-training
Converting to Keras format [train]:  25%|█████████████████████████▋                                                                              | 252/1018 [00:55<02:48,  4.53it/s]Traceback (most recent call last):
  File "cli.py", line 101, in <module>
    cli()
  File "/home/user9/anaconda3/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/user9/anaconda3/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/user9/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user9/anaconda3/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user9/anaconda3/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "cli.py", line 55, in build_keras_inputs
    kc.generate(max_length=NUM_FRAMES, counts_per_speaker=counts_per_speaker)
  File "/raid/user9/workspace/ASR/SpeakerVerification/deep-speaker-master/batcher.py", line 81, in generate
    kx_train, ky_train = self.generate_per_phase(max_length, counts_per_speaker[0], is_test=False)
  File "/raid/user9/workspace/ASR/SpeakerVerification/deep-speaker-master/batcher.py", line 75, in generate_per_phase
    for j, utterance_file in enumerate(np.random.choice(utterances_files, size=num_per_speaker, replace=True)):
  File "mtrand.pyx", line 1125, in mtrand.RandomState.choice
**ValueError: 'a' cannot be empty unless no samples are taken**
Exception ignored in: <function tqdm.__del__ at 0x7fa653c43e18>
Traceback (most recent call last):
  File "/home/user9/anaconda3/lib/python3.7/site-packages/tqdm/_tqdm.py", line 889, in __del__
    self.close()
  File "/home/user9/anaconda3/lib/python3.7/site-packages/tqdm/_tqdm.py", line 1095, in close
    self._decr_instances(self)
  File "/home/user9/anaconda3/lib/python3.7/site-packages/tqdm/_tqdm.py", line 454, in _decr_instances
    cls.monitor.exit()
  File "/home/user9/anaconda3/lib/python3.7/site-packages/tqdm/_monitor.py", line 52, in exit
    self.join()
  File "/home/user9/anaconda3/lib/python3.7/threading.py", line 1029, in join
    raise RuntimeError("cannot join current thread")
**RuntimeError: cannot join current thread**

> _there is an error when i run ./deep-speaker build_model_inputs_
did  you met  before?

**Comment by philipperemy** [comment]
@wenku1992abc I've never seen this error before.

```
ValueError: 'a' cannot be empty unless no samples are taken
```

But If I can bet, I'd say your folder `/raid/user9/workspace/ASR/SpeakerVerification/deep-speaker-master/pre-training/` should contain something.

**Comment by wenku1992abc** [comment]
how i check if something is containted in **pre-training/** folder?
I want to train a  mandarin voiceprint recognition model
so i used chinese corpus :_magicdata_ to generate the **pre-training/** folder

the _magicdata_ is .wav format
so i revised code in audio.py (line 41 42 )change ext='flac' to ext='wav'
and label also is changed to fit _magicdata_ datasets
the  **pre-training/** folder finished well by run ./deep-speaker build_mfcc

> class Audio:
> 
>     def __init__(self, cache_dir: str, audio_dir: str = None, sample_rate: int = SAMPLE_RATE, ext='wav'):

am i right to do this?

**Comment by philipperemy** [comment]
Yes, you have to change to WAV extension. WAV or FLAC is the same thing, just FLAC is the uncompressed WAV.
I don't remember in details. I would need to check the code again.

If you don't want to change the code to WAV you can also do that:

> If you have .wav, you can use ffmpeg to make the conversion. Both formats are flawless (FLAC is compressed WAV).

**Comment by wenku1992abc** [comment]
thanks!
i will check if something is containted in pre-training/ folder.

**Comment by wenku1992abc** [comment]
@philipperemy 
checked out !
it was one speaker whose recording just only one wav ~
i picked it out ,and code run normaly

the same as the last one speaker ,there is also another speaker met the same issue(only one wav~)
so i stop code ,picked out one speaker...
stop code ,picked out one speaker...
haha
if i can  i will add some code to pick it out  automatically

**Comment by philipperemy** [comment]
@wenku1992abc Great! Happy to hear. Yes, the code is not very robust. I implemented it for LibriSpeech (500 utterances per speaker at least). Please add a fix if you have time. Xie xie~
